---
- name: Install Docker and Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - python3-docker

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download apt key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: Add a key from a file
      ansible.builtin.apt_key:
        file: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        filename: docker.list
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt cache again
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Starting Docker service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Pull Kibana Docker image
      docker_image:
        name: elastic/kibana:7.17.9
        state: present

    - name: Create Docker Bridge Network
      docker_network:
        name: my_network
        driver: bridge

    - name: Run Kibana container
      docker_container:
        name: kibana
        image: elastic/kibana:7.17.9
        state: started
        restart_policy: unless-stopped
        network_mode: my_network
        published_ports: '5601:5601'
        env:
          ELASTICSEARCH_HOSTS: http://192.168.30.10:9200