- name: Zabbix Agent Installation
  hosts: web_servers #, kibana, elasticsearch, bastion
  become: yes
  tasks:
    - name: Downloading zabbix-release pkg
      get_url:
        url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb

    - name: Installing zabbix-release pkg
      shell: dpkg -i /tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb

    - name: apt update
      apt:
        update_cache: yes

    - name: Installing zabbix-agent
      apt:
        name: zabbix-agent
        state: present
    
    - name: Configure Zabbix agent
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server=0.0.0.0/0' }
        - { regexp: '^ServerActive=', line: '#ServerActive=' }
        - { regexp: '^Hostname=', line: '#Hostname=Zabbix server' }
    
    - name: Restarting zabbix-agent
      service:
        name: zabbix-agent
        state: restarted

    - name: Autorun zabbix-agent
      service:
        name: zabbix-agent
        enabled: yes