---
- name: Install Docker and Elasticsearch
  hosts: elasticsearch
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - python3-docker

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download apt key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: Add a key from a file
      ansible.builtin.apt_key:
        file: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        filename: docker.list
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt cache again
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Starting Docker service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Pull Elasticsearch Docker image
      docker_image:
        name: elasticsearch:7.17.9
        source: pull

    - name: Create Docker Bridge Network
      docker_network:
        name: my_network
        driver: bridge

    - name: Run Elasticsearch container
      docker_container:
        name: elasticsearch
        image: elasticsearch:7.17.9
        state: started
        restart_policy: unless-stopped
        network_mode: my_network
        published_ports:
           - "9200:9200"
           - "9300:9300"
        env:
          discovery.type: single-node
          xpack.security.enabled: "true"
          xpack.license.self_generated.type: basic
          ELASTIC_USERNAME: "elastic"
          ELASTIC_PASSWORD: "mypassword"
          xpack.security.authc.realms.native.native1.order: "0"